package:
  name: kgt_mslt
  version: 1.0.0

source:
  url: https://github.com/genomicepidemiology/kmergenetyper/archive/refs/tags/v1.0.16.tar.gz #change


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3.6
    - pip
    - kma >=1.4.9
  run:
    - python >=3.6
    - kma >=1.4.9
    - kmergenetyper >=1.0.16
about:
  home: https://github.com/genomicepidemiology/kmergenetyper
  summary: 'Kmergenetyper test.'
  license: Apache-2.0