package:
  name: kgt_mslt
  version: 1.0.0

source:
  url: https://github.com/genomicepidemiology/kgt_mslt/archive/refs/tags/v1.0.0.tar.gz


build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - kma >=1.4.9
    - kmergenetyper >=1.0.16
about:
  home: https://github.com/genomicepidemiology/kgt_mlst
  summary: 'kgt_mlst test.'
  license: Apache-2.0